### ISSUE TITLE
Rake Task to Upload Documentation

### ISSUE THREAD

**Issue by cfis** [ruby-rice/rice#181]
Would it be possible to make a Rake task to upload documentation? I forgot where Rice docs get uploaded to - is it https://github.com/jasonroelofs/jasonroelofs.github.io?

Should Rice docs move to a Rice group or similar in github?

**Comment by jasonroelofs** [comment]
The docs are via Github Pages for this repo (the `gh-pages` branch) so it is possible to do a rake task, though not trivial. How I have it set up is I have a second clone of the repo checked out to the `gh-pages` branch. Then I run `rake doc`, copy `doc/_build/html` to the gh-pages `4.x` directory, commit and push.

**Comment by cfis** [comment]
I see. I thought gh-pages branch were a thing of the past? And now its better to have a separate repo?

**Comment by jasonroelofs** [comment]
No I think that's just two different ways of serving up content depending on what you want the URL to be. We would need to change to a standalone repo if we wanted to move the docs to live at something like `rice.github.io`.

**Comment by cfis** [comment]
Revisiting this...yeah the separate repo is what I did for ruby-prof. What do you think about doing that for Rice?

**Comment by jasonroelofs** [comment]
I'm not against the idea. `gh-pages` is a bit cumbersome to deal with.

**Comment by jasonroelofs** [comment]
Thinking about this more, maybe it's time to move this into it's own org. github.com/ruby-rice/rice?

**Comment by cfis** [comment]
Sounds good to me.

**Comment by cfis** [comment]
Going to close this since the documentation moved to its own repo.
