### ISSUE TITLE
Version access

### ISSUE THREAD

**Issue by uvlad7** [ruby-rice/rice#214]
`version.rb` doesn't follow standard Ruby directory hierarchy style for namespacing, it should be `rice/version.rb` (or `rice-version.rb`), currently it can be required by simply `require "version"`, which is not OK.
 
For easy fix it's possible to just add `require_relative 'version'` into `mkmf-rice.rb`, so weird `require "version"` is not needed, but `version` is still added to the load path in that case and it might unexpectedly shadow other files.

**Comment by cfis** [comment]
I'm good with this change.

**Comment by cfis** [comment]
See https://github.com/ruby-rice/rice/pull/215
