### ISSUE TITLE
Error in Ubuntu 14.10

### ISSUE THREAD

**Issue by cajahyba** [ruby-rice/rice#73]
Hi, I am getting an error when I try to install rice gem in Ubuntu 14.10:

$ gem install rice
Building native extensions.  This could take a while...
ERROR:  Error installing rice:
        ERROR: Failed to build gem native extension.

```
/usr/bin/ruby2.1 extconf.rb
```

bootstrap: 4: bootstrap: autoreconf: not found
post-autoconf.rb:6:in `initialize': No such file or directory @ rb_sysopen - configure (Errno::ENOENT)
        from post-autoconf.rb:6:in`open'
        from post-autoconf.rb:6:in `process'
        from post-autoconf.rb:16:in`<main>'
Post-processing configure
sh: 0: Can't open configure

Makefile not found

Thanks!

**Comment by Jesse-V** [comment]
I just experienced this issue in Mint 17.1 (Ubuntu 14.04). It would be great if I had a better message of what went wrong!

**Comment by jasonroelofs** [comment]
Yes, the install script could definitely use an extra check and give a better error message when dependencies don't exist. It's on my list!
